### ISSUE TITLE
Issue on creation of a content

### ISSUE THREAD

**Issue by frague59** [feincms/django-content-editor#30]
Hi, 

I'm using django-content-editor to create some "pseudo-static" pages into a site, and I've an issue when I create a RichText into a page.

**I've only one region in the page - `main`**

+ Each time I add a RichText, or another block, when I save the page I've a message "Unknown region"

![Unknown region message](https://github.com/user-attachments/assets/3ff54f59-55be-4261-b468-6282c405a30b)

It seams the region is not pre-populated...

If I edit the page, I can see a small select on the top left of the pane where I can select the region "Main".

Thanks  !

**Comment by frague59** [comment]
django 4.2, last version of django-content-editor

**Comment by matthiask** [comment]
@frague59 Oh no. I wonder what's going on. Can you share the model and admin definition?

**Comment by matthiask** [comment]
(I cannot reproduce the problem in my project here, so being able to have a look at your code might be helpful!)

**Comment by frague59** [comment]
+ Models : https://gist.github.com/frague59/24a68a4ba17c716018f4800ab9eac643
+ Admin : https://gist.github.com/frague59/0cb4b4879197fb9a219418ddef3c2822

**Comment by matthiask** [comment]
Thanks! The problem seems to be that `ordering` and `region` are in a sub-fieldset. It seems to work if you use 

```python
                "fields": [
                    "title",
                    "image",
                    "position",
                    "credit",
                    # ("ordering", "region"),
                    "ordering",
                    "region",
                ]
```

Still, this has to be fixed. I'm looking into it now.

**Comment by frague59** [comment]
I've tried to remove the grouping, same issue...

**Comment by frague59** [comment]
When debugging with firefox, I can see on `<div id="cms_richtext_set-1"` `data-region="__unknown__" `
Look's like a initialization issue on the creation on the widget

**Comment by matthiask** [comment]
The code is now more careful when identifying the region and ordering fields; I'm quite confident that this fixes the issue. Could you test 7.0.11 to see if the problem still happens? Thanks for your help identifying the issue.

**Comment by frague59** [comment]
Hi, 
I just saw you require python 3.10+, I'm on python 3.9 (debian oldstable on the server)
I'l try upgrading my python version on the dev, and see if it works now...

**Comment by frague59** [comment]
Same issue - python 3.10 + django 4.2 + django-content-editor 7.0.11

**Comment by matthiask** [comment]
I believe you, but it's also super strange. I wonder if my package building strategy is broken and you are getting old assets for some reason. Also, sorry for raising the Python version requirement in a patch release, I'll revert that for now.

**Comment by matthiask** [comment]
I'm sorry but I really have no idea what the problem could be now. I have tested the code on several projects with multiple `fieldsets` configurations and variations. I could reproduce the bug earlier when using `... "fields": [..., ("ordering", "region")] ...` but now it works all the time every time.

**Comment by frague59** [comment]
Hi, 

... if it can help... I continue digging around the JS. 

I can say the `id_cms_richtext_set-2-region` field is empty when I create a new richtext block. Then on submit, the field is empty in the POST request, driving to the form error.

![image](https://github.com/user-attachments/assets/5a52b0e8-9690-4180-95b0-6ab31ecf1b53)
.

**Comment by matthiask** [comment]
Yes, it's expected that this is empty in the HTML. What should happen is:

- Django's inlines.js triggers `formset:added` which runs `handleFormsetAdded`: https://github.com/feincms/django-content-editor/blob/a546f6899438c0db3228b36c42629286e7f2fbd4/content_editor/static/content_editor/content_editor.js#L726
- `handleFormsetAdded` fills in the region field with the current region: https://github.com/feincms/django-content-editor/blob/a546f6899438c0db3228b36c42629286e7f2fbd4/content_editor/static/content_editor/content_editor.js#L672-L674

Is the region field also empty if you run `document.getElementById("id_cms_richtext_set-2-region").value` in the console?

**Comment by frague59** [comment]
Yes, it is empty. That's the problem... I'd already figured out the mechanics : using inlines.js to trigger the 'formset:added' event, update local settings it in `handleFormsetAdded`.

Maybe an issue with CKEditor 5 from django-ckeditor-5 ? I've some issues on browser console.

`Uncaught TypeError: e.matches is not a function`

(Debugging in "modern" browsers in a pain...)

**Comment by matthiask** [comment]
> Maybe an issue with CKEditor 5 from django-ckeditor-5 ? I've some issues on browser console.

Hmm. Yes, that could be it. Does it work when you remove the CKEditor5 widget? 

I took a look at the initialization code here https://github.com/hvlads/django-ckeditor-5/blob/master/django_ckeditor_5/static/django_ckeditor_5/app.js. It seems to me that the `formset:added` signal is handled in a strange way:

https://github.com/hvlads/django-ckeditor-5/blob/9081d37ae5fe1078e25c72962b6a4e95d218c540/django_ckeditor_5/static/django_ckeditor_5/app.js#L155-L157

The first argument to `createEditors` is the event, but `createEditors` expects a root element in which to find editor nodes. Does it work if you change the line to `django.jQuery(document).on("formset:added", () => { createEditors() });`? That would mean it's a django-ckeditor-5 bug. This still wouldn't explain why our code (which assigns the region value) doesn't run...

(Let's reopen the issue since we're still discussing this.)

**Comment by frague59** [comment]
Hi,

I've tried WITHOUT django-ckeditor-5 - It works !

I've opened an issue on this project. 

https://github.com/hvlads/django-ckeditor-5/issues/253

Thanks !

**Comment by matthiask** [comment]
Thank you!
